# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5e8caea4e3dc6fa1a18249c17ef4856ae9cba16587aab9826d45caf1fff0b1f55b79822ba2767c1741032411a758c71c589deaa8e75a55e23ea35329fe7db0

test:
  secret_key_base: 5d1ef86c355b769e3339321bfc31149fafc5f4700af7c6eb75c274f66b88f763c5171694c2d6fe54e8ed318af2086d8c9252b86928e2b8e79594afdfd91cb720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
